; DO NOT EDIT -- generated by `npm run i18n:generate` (scripts/i18n-generate.mjs).
; Source of truth: locales/ko/*.json. Boron translation-overlay fragment:
; each line maps one semantic ID (module/TLK/binary display entries) to
; its Korean display text. Consumed by the config_boron translation
; overlay path; internal command keys are never emitted here.
ko-translations: [
]
